main: plugin.Commands
version: 1.0
name: Twitter4Miner
author: @cupOjoseph
commands:
  tweet:
    description: Make a tweet!
    usage: /<command> [Message]
  tlogin:
    description: Login to your twitter account IN MINECRAFT!
    usage: /<command>
  tlogout:
    description: Log out of Twitter on this server.
    usage: /<command>
